### ISSUE TITLE
Not able to send message, it throws 404 room not found

### ISSUE THREAD

**Issue by radhinesh** [rustyxlol/Django-ChatApp#4]
![image](https://github.com/user-attachments/assets/07a379d9-7813-4e4f-afc7-b9f2cc50a5d7)

**Comment by baturez** [comment]
did you fix that issue bro ?

**Comment by rustyxlol** [comment]
Hi guys, sorry for the late response, I didn't get notification for this issue. 

Let me check it and get back to you

**Comment by rustyxlol** [comment]
Hi guys @baturez / @radhinesh,  Thank you for pointing this out!

My apologies for not putting the version or the library in requirements.txt.

This issue is due to channels 4 which does not seem to start ASGI server anymore because it has been decoupled.

To fix this issue, simply do the following
```
pip uninstall channels
pip install channels==3.0.5
```

Please check this SO answer for more information or alternate solution using channels 4 package: https://stackoverflow.com/a/76188119/16024991

I will update the requirements.txt soon™️

**Comment by baturez** [comment]
> channel
thx man i solved before you reply channels don't work on version 3.0.5<

**Comment by baturez** [comment]
and i get a different issue boostrap4 i solved that issue in this way 
INSTALLED_APPS = [
    'channels',
    'crispy_forms',
    'bootstrap4',
    'crispy_bootstrap4',
    'chat.apps.ChatConfig',
    'users.apps.UsersConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
CRISPY_TEMPLATE_PACK = 'bootstrap4'

i download 'bootstrap4', and
    'crispy_bootstrap4', it solved

**Comment by rustyxlol** [comment]
Yeah I came across that while running, fixed the same in PR as well! I believe just `pip install crispy-bootstrap4` and adding `crispy_bootstrap4` in INSTALLED_APPS works just as well!
